version: '3'

volumes:
  db-data:
    driver: local

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/ess'
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2
    depends_on: 
      - db
    links:
      - db

  db:
    image: mysql:5.7
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: <%= ENV["MYSQL_ROOT_PASSWORD"] %>
      MYSQL_DATABASE: ess_development
      MYSQL_USERNAME: <%= ENV["MYSQL_USERNAME"] %>
    volumes:
      - 'db-data:/var/lib/mysql'
    


      
 