version: '3'

volumes:
  db-data:
    driver: local

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/ess'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_USER: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
      MYSQL_ROOT_PASSWORD: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
    volumes:
      - 'db-data:/var/lib/mysql'


      
 