version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@01.0.0

jobs:
  build:
    docker:
    - image: circleci/ruby:2.5.3
      environment:
         BUNDLER_VERSION: 2.0.2
         RAILS_ENV: test
         
    - image: circleci/mysql:5.7-ram
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
         MYSQL_HOST: 127.0.0.1
         MYSQL_USERNAME: root
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: ess_test
  
    working_directory: ~/ess  
  

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.0.2
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # Database setup
    - run:
        name: Databasesetup
        command: |
           bundle exec rake db:create
           bundle exec rake db:schema:load

    # run tests! (RSpec)
    - run:
        name: Run rspec
        command: bundle exec rspec

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results 
  deploy:
    docker:
      - image: buildpack-deps:trusty
    executor: heroku/default
    steps: 
      - checkout
      - run:
          name: deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build-deploy:
    jobs:
      
      - build 
      - deploy:
          requires: 
            - build
          filters:
            branches:
              only: master